### ISSUE TITLE
Session log_function printing sensitive information / not behaving as expected

### ISSUE THREAD

**Issue by GreyArea765** [zadarastorage/zadarapy#2]
Either I'm not understanding the behaviour of log_function in session.Session() or its behaviour is a bit odd.
I'm using zadarapy as a module and during testing I noticed that sensitive information (API Key) was being printed to stdout.  This seemed less than ideal so I took a look.

The Docstring for Session.init() has the log_function parameter documented as:

```python
        """
        :type log_function: function
        :param log_function: Function variable to a log function to print the
                API command Session sends. Default=None, means no print
        """
```

However in the implementation we see the following:

```python
        if not self._log_function:
            print("API: " + msg)
            return

        self._log_function(msg)
```

To me this read as if the log_function is not set, the API call details are printed, including the senstive API key which is in opposition the Docstring statement.  Then it seems that a log function is attempted to be called regardless of whether we have set one or not.

It seems like this is not behaving as expected and regardless, the API key should be filtered out of any console/log output in my view (I would prefer it didn't).

**Comment by noga1290** [comment]
@GreyArea765 - fixed over commit 03ff361cb8be56d0774e06240b82c1312588bc93.
